# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a34177f3bc7b73df344a6e8b764e19cf5a7a181c079360660253e3a66a53db3bd2d3e1ea7f251d30df7ec8d1cdd48148c97fd52634271bba90e7d165f8153428

test:
  secret_key_base: 2fd8146993a664d444925484bca5bdb10451083b9179a77439042613c14692f4083256983047cd1e070309ef91e17fb4032f94b2cea0cf9c6acbde569a24835d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
